### ISSUE TITLE
增加网页访问chatgpt的方式

### ISSUE THREAD

**Issue by myreality** [yqchilde/wxbot#13]
目前使用的是openai API访问，参考这个https://github.com/lss233/chatgpt-mirai-qq-bot ，期待未来支持使用网页版方式访问最新的chatgpt。

**Comment by yqchilde** [comment]
你指出的项目依赖项目 [https://github.com/acheong08/ChatGPT](https://github.com/acheong08/ChatGPT)

这个项目要实现不能纯go实现，先不考虑了
