### ISSUE TITLE
有没有部署方法？

### ISSUE THREAD

**Issue by badboycxcc** [yqchilde/wxbot#2]
能不能简单提一下部署方法？

**Comment by yqchilde** [comment]
我抽空完善一下文档

1. 需要有一个vx框架，比如[千寻](https://gitee.com/qxvxhook/pc-vx-hook-http-api)
2. 在一台windows pc电脑上打开千寻，请查看千寻相关文档
3. 如果在本地跑，直接clone代码，修改config.yaml，并 go run main即可
4. 如果用docker跑请点开docker目录查看

需要说明的是，本项目只是用于hook类微信接收消息回调并处理的一个项目，在这类hook项目上都有HTTP转发，即pc机器上vx监听到消息变化通过http推送给该项目，该项目是一个server

**Comment by badboycxcc** [comment]
ok
