### ISSUE TITLE
重新编译出错，大佬指导下

### ISSUE THREAD

**Issue by cjumna** [yqchilde/wxbot#45]
小白，不太懂怎么编译，自己在chatGPT稍作修改，可是今天发现更新1.4后有个web插件，编译始终不过，还请大佬指导下哪里出错了。
root:/volume2/docker/wxbot/wxbot-1.5.0# docker image build -t yqchilde/wxbot:v1.5.0 .
Sending build context to Docker daemon  22.36MB
Step 1/19 : FROM golang:1.19-alpine as builder
 ---> feb4bbda921c
Step 2/19 : ENV GOPROXY="https://goproxy.cn,direct"
 ---> Using cache
 ---> fe3cfd0f3543
Step 3/19 : ARG VERSION
 ---> Using cache
 ---> bc436d7cd61f
Step 4/19 : WORKDIR /app/
 ---> Using cache
 ---> 0d0583c5e232
Step 5/19 : COPY go.mod .
 ---> 67d0db210f41
Step 6/19 : COPY go.sum .
 ---> dc444d486073
Step 7/19 : RUN go generate -tags plugins ./engine/plugins
 ---> Running in 4f56f5e5a431
Removing intermediate container 4f56f5e5a431
 ---> 4186c36ad119
Step 8/19 : RUN go mod download
 ---> Running in 2ff03746e437
Removing intermediate container 2ff03746e437
 ---> 95d36f127613
Step 9/19 : COPY . .
 ---> cf76a8367b4e
Step 10/19 : RUN CGO_ENABLED=0 go build -ldflags="-s -w -X github.com/yqchilde/wxbot/engine/robot.version=${VERSION}" -o ./bin/wxbot
 ---> Running in 61d41e0247ff
web/web.go:8:1: expected 'package', found '<'
The command '/bin/sh -c CGO_ENABLED=0 go build -ldflags="-s -w -X github.com/yqchilde/wxbot/engine/robot.version=${VERSION}" -o ./bin/wxbot' returned a non-zero code: 1

这个是web文件夹空的，我手动下载的文件
![屏幕截图 2023-03-04 202412](https://user-images.githubusercontent.com/46271329/222901073-f4e38cbc-878d-48f8-94f1-79bd3c13c39e.png)

**Comment by yqchilde** [comment]
web.go可能是空的，可以重新克隆一份代码复制过去整个web文件夹，记住命令有变化，请查看这里
https://github.com/yqchilde/wxbot#%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C

如果问题描述不清可以来交流群问我

**Comment by cjumna** [comment]
搞定了，用go环境跑不会文件缺失
