### ISSUE TITLE
gpt3 好像没法连续对话

### ISSUE THREAD

**Issue by kirbystudy** [yqchilde/wxbot#5]

**Comment by yqchilde** [comment]
可以连续，但是每次都要带上前缀 `#`

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/36953759/206900355-22ba7435-4f6e-462a-ab9a-ec83d11c3404.png">

**Comment by kirbystudy** [comment]
连着对话 都是回复收到您的问题了,正在构建上下文中,由于训练我的工程师将我放在了大陆另一端,所以回复可能会有点慢噢~
是哪里的问题呢?

**Comment by yqchilde** [comment]
你在调试吗，每次重新启动项目也会重新开始

这是因为上下文没有入库，数据都在内存中，当每次项目重启就会从头开始

**Comment by kirbystudy** [comment]
不是调试，我部署到了服务器里运行

**Comment by kirbystudy** [comment]
我想问一下FromUniqueID 这个是消息的id 还是？

**Comment by yqchilde** [comment]
消息来源唯一id, 私聊为发送者微信id, 群聊为群id

**Comment by kirbystudy** [comment]
我应该是这里写错了，感谢大佬指正。
