### ISSUE TITLE
Chatgpt 代理问题

### ISSUE THREAD

**Issue by evan-xie** [yqchilde/wxbot#50]
我机器开了梯子的情况下网页可以打开https://api.openai.com/v1/chat/completions，但是回答依然是
`ChatGPT出错了，Err：Post "https://api.openai.com/v1/chat/completions": dial tcp 199.16.158.182:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`
是必须开做一个代理页面？

**Comment by yqchilde** [comment]
程序没走代理，尝试全局
或者本地搭一个代理，用`set chatgpt proxy https://你的地址/v1`
本地代理项目可参考 [https://github.com/yqchilde/openai-proxy](https://github.com/yqchilde/openai-proxy)

**Comment by MQpeng** [comment]
#57 同遇这个问题，开了一个PR

**Comment by evan-xie** [comment]
使用了全局依然没有解决，使用了proxifier加代理
![image](https://user-images.githubusercontent.com/16145657/224202679-a2e0b018-757e-4ce3-bfa5-ac98fe463cde.png)

**Comment by yqchilde** [comment]
两种方式解决这个问题：
1. 利用反向代理，代理一下`api.openai.com`这个网站，比如你代理到`api.abc.com`，那你可以使用指令 `set chatgpt proxy http://api.abc.com/v1`
2. `wxbot`所在机器你开了代理，这时候你可以使用网络代理，比如clash的端口是`7890`，那你可以使用指令 `set chatgpt http_proxy http://127.0.0.1:7890`，下次访问openai网站时会走你的代理去访问，如果不是clash，其他软件同理
