### ISSUE TITLE
问下 docker下plugins的main.go文件哪里可以找到?

### ISSUE THREAD

**Issue by cjumna** [yqchilde/wxbot#8]
我想修改下提示的信息,没到这个文件....这个插件在哪里? 谢谢

**Comment by yqchilde** [comment]
改哪个插件就去plugins目录下对应插件文件夹里去改，改完重新编译运行

![image](https://user-images.githubusercontent.com/36953759/217984066-2af1b76a-89f2-4e86-b365-b511697cd149.png)

**Comment by cjumna** [comment]
新手,不会自己编译.我用docker文件,可不可以把插件库映射到data下

**Comment by yqchilde** [comment]
目前还不是动态插件😭，插件整体是编译进去的，所以还不支持

**Comment by cjumna** [comment]
加油，你这个软件我用起来很方便. 避免了直接扫描登录后被微信警告！
