### ISSUE TITLE
千寻最近封的严重吗？

### ISSUE THREAD

**Issue by Klaus-Kin** [yqchilde/wxbot#88]
emm~
好久没用了

**Comment by yqchilde** [comment]
是的，请使用大恩（Dean DLL），千寻代码近期会移除，隔不久就会被扫号

**Comment by Klaus-Kin** [comment]
> 是的，请使用大恩（Dean DLL），千寻代码近期会移除，隔不久就会被扫号

好的 谢谢佬  刚想加入组织  q群满员...可惜

**Comment by Klaus-Kin** [comment]
> 是的，请使用大恩（Dean DLL），千寻代码近期会移除，隔不久就会被扫号

而且大恩文档404啊

**Comment by yqchilde** [comment]
> > 是的，请使用大恩（Dean DLL），千寻代码近期会移除，隔不久就会被扫号
> 
> 好的 谢谢佬 刚想加入组织 q群满员...可惜

已扩充群人数
大恩文档地址：https://www.apifox.cn/apidoc/shared-af49a169-8b5c-4137-a5ea-723a10e8e794/doc-1093376
文档密码: vHCAG7IM

**Comment by Klaus-Kin** [comment]
加油~
