### ISSUE TITLE
听说西瓜框架很稳

### ISSUE THREAD

**Issue by Klaus-Kin** [yqchilde/wxbot#89]
佬有没有添加西瓜框架的计划？

**Comment by Klaus-Kin** [comment]
另：
1.readme的开发计划url404了
2.大恩框架 apifox的文档中，DaenWxHook.dll、Daen注入器、HPSocket4C.dll的下载地址也挂了

**Comment by yqchilde** [comment]
> 佬有没有添加西瓜框架的计划？

接的vlw代指的就是西瓜框架，西瓜是vlw改的，用xyo插件，交流群群文件有文件包
大恩的其他文件在这里 https://gitee.com/qxvxhook/pc-vx-hook-http-api/tree/36018/DaenWxHook

**Comment by Klaus-Kin** [comment]
> 接的vlw代指的就是西瓜框架，西瓜是vlw改的，用xyo插件，交流群群文件有文件包 大恩的其他文件在这里 https://gitee.com/qxvxhook/pc-vx-hook-http-api/tree/36018/DaenWxHook

收到 谢谢~群里的vlw是配合压缩包里的抓包一起用的吧？另外看到您在git 提交记录中是说更推荐大恩？

**Comment by yqchilde** [comment]
> > 接的vlw代指的就是西瓜框架，西瓜是vlw改的，用xyo插件，交流群群文件有文件包 大恩的其他文件在这里 https://gitee.com/qxvxhook/pc-vx-hook-http-api/tree/36018/DaenWxHook
> 
> 收到 谢谢~群里的vlw是配合压缩包里的抓包一起用的吧？另外看到您在git 提交记录中是说更推荐大恩？

是配合抓包一起用，大恩和西瓜都行吧，我最近一直用大恩

**Comment by Klaus-Kin** [comment]
> > > 接的vlw代指的就是西瓜框架，西瓜是vlw改的，用xyo插件，交流群群文件有文件包 大恩的其他文件在这里 https://gitee.com/qxvxhook/pc-vx-hook-http-api/tree/36018/DaenWxHook
> > 
> > 
> > 收到 谢谢~群里的vlw是配合压缩包里的抓包一起用的吧？另外看到您在git 提交记录中是说更推荐大恩？
> 
> 是配合抓包一起用，大恩和西瓜都行吧，我最近一直用大恩

get~谢谢
